table _Medidas
	lineageTag: a84cffb2-cca5-48c0-b65b-519145e65e2b

	measure 'Média Móvel 3M Vendas' =
			
			VAR UltimaDataComVenda = MAX('fato_vendas'[Data do Pedido])
			VAR DataAtualContexto = MAX('Dim_Calendario'[Date])
			VAR Periodo = DATESINPERIOD('Dim_Calendario'[Date], DataAtualContexto, -3, MONTH)
			
			RETURN
			IF(
			    DataAtualContexto <= UltimaDataComVenda,
			    AVERAGEX(Periodo, [Total Sales]),
			    BLANK()
			)
		lineageTag: d056560d-8d46-45a1-a98f-f72351879c9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = DIVIDE(SUM('fato_vendas'[Lucro do Pedido]), [Total Sales], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 17eef69a-97ad-42f9-8d05-bf5985edc560

	measure 'OTD %' = ```
			
			VAR PedidosNoPrazo = 
			    CALCULATE(
			        DISTINCTCOUNT('fato_vendas'[ID do Pedido]), 
			        'fato_vendas'[No Prazo Flag] = 1
			    )
			VAR TotalDePedidos = [Total Orders]
			RETURN 
			    DIVIDE(PedidosNoPrazo, TotalDePedidos, 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ba6a6adc-2474-49c4-a208-eb0c5872a213

	measure 'Total Orders' = DISTINCTCOUNT('DataCoSupplyChainDataset'[Order Id])
		formatString: 0
		lineageTag: 20ce25a0-bb3c-4aec-afe7-7bae61b92d66

	measure qtde_vendas =
			
			CALCULATE(
			    DISTINCTCOUNT('fato_vendas'[ID do Pedido]),
			    'fato_vendas'[Status do Pedido] <> "Cancelado"
			)
		formatString: 0
		lineageTag: 173a6462-4c25-4733-8ec1-4a0b67b52156

	measure 'Total Sales' = SUM('fato_vendas'[Vendas])
		lineageTag: 7469e5a6-2934-4997-b6dc-5d850091a84d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SLA Sugerido (P90)' = ```
			
			PERCENTILEX.INC(
			    'fato_vendas', 
			    'fato_vendas'[Dias Envio Real], 
			    0.90
			)
			```
		lineageTag: bd44ecc4-fd06-4df3-ac59-e20d730e1b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SLA para 100% OTD' = MAX('fato_vendas'[Dias Envio Real])
		formatString: 0
		lineageTag: 0154fba7-9ca5-453b-aa46-b50686c0a5a3

	measure 'OTD % (SLA Atual)' = ```
			
			VAR PedidosNoPrazo = 
			    CALCULATE(
			        [Total Orders], 
			        'fato_vendas'[No Prazo Flag] = 1
			    )
			RETURN 
			    DIVIDE(PedidosNoPrazo, [Total Orders], 0)
			```
		lineageTag: a3e0c22d-936d-49ab-a2b9-0f088bcb7504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: ea6bcb9d-48c4-480a-8dc0-5853d843818f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b0e2d989e9384c34b5bc2b7b13a7412b

