table _Medidas
	lineageTag: a84cffb2-cca5-48c0-b65b-519145e65e2b

	measure 'Média Móvel 3M Vendas' = ```
			
			VAR MesesVisiveis = 3
			VAR UltimaData = MAX('Dim_Calendario'[Date])
			VAR Periodo = 
			    DATESINPERIOD(
			        'Dim_Calendario'[Date], 
			        UltimaData, 
			        -MesesVisiveis, 
			        MONTH
			    )
			RETURN
			    IF(
			        ISFILTERED('Dim_Calendario'[Date]),
			        AVERAGEX(
			            Periodo,
			            [Total Sales] -- Certifique-se de já ter uma medida simples de [Total Sales]
			        ),
			        BLANK()
			    )
			```
		lineageTag: d056560d-8d46-45a1-a98f-f72351879c9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = DIVIDE(SUM('fato_vendas'[Lucro do Pedido]), [Total Sales], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 17eef69a-97ad-42f9-8d05-bf5985edc560

	measure 'OTD %' = ```
			
			VAR PedidosNoPrazo = 
			    CALCULATE(
			        [Total Orders], 
			        'fato_vendas'[Dias Envio Real] <= 'fato_vendas'[Dias Envio Programado]
			    )
			RETURN 
			    DIVIDE(PedidosNoPrazo, [Total Orders], 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ba6a6adc-2474-49c4-a208-eb0c5872a213

	measure 'Total Orders' = DISTINCTCOUNT('DataCoSupplyChainDataset'[Order Id])
		formatString: 0
		lineageTag: 20ce25a0-bb3c-4aec-afe7-7bae61b92d66

	measure qtde_vendas =
			
			CALCULATE(
			    DISTINCTCOUNT('fato_vendas'[ID do Pedido]),
			    'fato_vendas'[Status do Pedido] <> "Cancelado"
			)
		formatString: 0
		lineageTag: 173a6462-4c25-4733-8ec1-4a0b67b52156

	measure 'Total Sales' = SUM('fato_vendas'[Vendas])
		lineageTag: 7469e5a6-2934-4997-b6dc-5d850091a84d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: ea6bcb9d-48c4-480a-8dc0-5853d843818f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b0e2d989e9384c34b5bc2b7b13a7412b

