table DataCoSupplyChainDataset_transformed
	lineageTag: 94ad62b2-a773-4fac-bbd6-a49043df91ed

	column Type
		dataType: string
		lineageTag: b1b87255-2f78-4c71-998e-cb1b89e25e61
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Days for shipping (real)'
		dataType: int64
		formatString: 0
		lineageTag: 9241d826-a9ed-411f-865d-734740680e62
		summarizeBy: sum
		sourceColumn: Days for shipping (real)

		annotation SummarizationSetBy = Automatic

	column 'Days for shipment (scheduled)'
		dataType: int64
		formatString: 0
		lineageTag: 7b666a4c-b8b2-497b-8d0d-7052923d0e59
		summarizeBy: sum
		sourceColumn: Days for shipment (scheduled)

		annotation SummarizationSetBy = Automatic

	column 'Benefit per order'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ccba62d7-f0d0-4a1b-9c60-c231f01c38f2
		summarizeBy: sum
		sourceColumn: Benefit per order

		annotation SummarizationSetBy = Automatic

	column 'Sales per customer'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 05d7003f-2491-4f69-a1e5-bf9dffd9ffac
		summarizeBy: sum
		sourceColumn: Sales per customer

		annotation SummarizationSetBy = Automatic

	column 'Delivery Status'
		dataType: string
		lineageTag: a54506f9-c60f-4b31-b28a-8583873e3648
		summarizeBy: none
		sourceColumn: Delivery Status

		annotation SummarizationSetBy = Automatic

	column Late_delivery_risk
		dataType: int64
		formatString: 0
		lineageTag: 5e2158db-3493-4400-8d50-688dccd4b605
		summarizeBy: sum
		sourceColumn: Late_delivery_risk

		annotation SummarizationSetBy = Automatic

	column 'Category Id'
		dataType: int64
		formatString: 0
		lineageTag: fb223b2a-170b-4c6f-be53-8047d67aa6b8
		summarizeBy: count
		sourceColumn: Category Id

		annotation SummarizationSetBy = Automatic

	column 'Category Name'
		dataType: string
		lineageTag: 0baacfd5-5826-4ca7-9903-5d1144d9cb02
		summarizeBy: none
		sourceColumn: Category Name

		annotation SummarizationSetBy = Automatic

	column 'Customer City'
		dataType: string
		lineageTag: 2262df1d-7dad-462e-b613-0b7f1933f74d
		summarizeBy: none
		sourceColumn: Customer City

		annotation SummarizationSetBy = Automatic

	column 'Customer Country'
		dataType: string
		lineageTag: a432cc7b-3d56-4984-ad46-e7055d09496f
		summarizeBy: none
		sourceColumn: Customer Country

		annotation SummarizationSetBy = Automatic

	column 'Customer Email'
		dataType: string
		lineageTag: 7e42ceb4-b5b1-4ad8-a0f2-b4c3bb5a1dac
		summarizeBy: none
		sourceColumn: Customer Email

		annotation SummarizationSetBy = Automatic

	column 'Customer Fname'
		dataType: string
		lineageTag: 07878207-214e-40d4-96b7-96ff035caf3c
		summarizeBy: none
		sourceColumn: Customer Fname

		annotation SummarizationSetBy = Automatic

	column 'Customer Id'
		dataType: int64
		formatString: 0
		lineageTag: 49e11bfc-07bd-4ef4-a378-0e76b200aec5
		summarizeBy: count
		sourceColumn: Customer Id

		annotation SummarizationSetBy = Automatic

	column 'Customer Lname'
		dataType: string
		lineageTag: 48c42847-5913-464f-9c75-aff58ab94eff
		summarizeBy: none
		sourceColumn: Customer Lname

		annotation SummarizationSetBy = Automatic

	column 'Customer Password'
		dataType: string
		lineageTag: 493f6d5e-bbb0-4395-8550-fb938ad31fb2
		summarizeBy: none
		sourceColumn: Customer Password

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: e5db237e-e752-4ba9-a150-2f60a7f39261
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column 'Customer State'
		dataType: string
		lineageTag: dcec36a7-5bf1-4497-b326-7df4540e02c6
		summarizeBy: none
		sourceColumn: Customer State

		annotation SummarizationSetBy = Automatic

	column 'Customer Street'
		dataType: string
		lineageTag: 05d60e76-8f70-4f88-9d12-98b8a2415aed
		summarizeBy: none
		sourceColumn: Customer Street

		annotation SummarizationSetBy = Automatic

	column 'Customer Zipcode'
		dataType: int64
		formatString: 0
		lineageTag: 85cbfb5b-6a33-4c58-82d5-88a7a99f0a8a
		summarizeBy: sum
		sourceColumn: Customer Zipcode

		annotation SummarizationSetBy = Automatic

	column 'Department Id'
		dataType: int64
		formatString: 0
		lineageTag: 2083c572-e0b6-46aa-9626-400c1f003b3c
		summarizeBy: count
		sourceColumn: Department Id

		annotation SummarizationSetBy = Automatic

	column 'Department Name'
		dataType: string
		lineageTag: dc38a738-8069-4c32-b9b7-31dbc476515b
		summarizeBy: none
		sourceColumn: Department Name

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: int64
		formatString: 0
		lineageTag: ceee43d4-776b-4d25-819b-ee4b39eea219
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: int64
		formatString: 0
		lineageTag: 45e43667-6056-4593-a421-95d0f8622481
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 41e85882-197b-4b1b-ac9e-6b20302e54cb
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column 'Order City'
		dataType: string
		lineageTag: f0898126-3879-41d3-97b9-8c8d0fd955b4
		summarizeBy: none
		sourceColumn: Order City

		annotation SummarizationSetBy = Automatic

	column 'Order Country'
		dataType: string
		lineageTag: 19153aaf-b4f2-4ba0-b0e5-0f19c4777a7b
		summarizeBy: none
		sourceColumn: Order Country

		annotation SummarizationSetBy = Automatic

	column 'Order Customer Id'
		dataType: int64
		formatString: 0
		lineageTag: 86ce84ac-a06f-4b35-be0d-fb548769a72a
		summarizeBy: count
		sourceColumn: Order Customer Id

		annotation SummarizationSetBy = Automatic

	column 'order date (DateOrders)'
		dataType: dateTime
		formatString: Short Date
		lineageTag: c134d6c3-007a-4ae2-8d85-6e9270e17258
		summarizeBy: none
		sourceColumn: order date (DateOrders)

		variation Variation
			isDefault
			relationship: 62ae7547-f28d-4702-ab21-0b69cca64e54
			defaultHierarchy: LocalDateTable_3793822a-7b83-414b-b451-d5e0d67d8be5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Order Id'
		dataType: int64
		formatString: 0
		lineageTag: b886a493-0212-4a9f-8d2c-8797ac220c5a
		summarizeBy: count
		sourceColumn: Order Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Cardprod Id'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8ba77b8e-4443-4dc0-b67e-7623c9657ad7
		summarizeBy: count
		sourceColumn: Order Item Cardprod Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Discount'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5df14b66-b73a-4264-84cb-7b49ea22b9fd
		summarizeBy: sum
		sourceColumn: Order Item Discount

		annotation SummarizationSetBy = Automatic

	column 'Order Item Discount Rate'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b65acdc3-3836-483a-b9d9-eae2376ae40a
		summarizeBy: sum
		sourceColumn: Order Item Discount Rate

		annotation SummarizationSetBy = Automatic

	column 'Order Item Id'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ad1fc77a-5eac-46b6-af4e-b65368e7f357
		summarizeBy: count
		sourceColumn: Order Item Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Product Price'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 13d2231c-98c7-4ce5-8260-f5b202c40ddb
		summarizeBy: sum
		sourceColumn: Order Item Product Price

		annotation SummarizationSetBy = Automatic

	column 'Order Item Profit Ratio'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cbd96d22-c6a3-4de0-bfce-dcd3da22a347
		summarizeBy: sum
		sourceColumn: Order Item Profit Ratio

		annotation SummarizationSetBy = Automatic

	column 'Order Item Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 0faf7ad9-d87b-4b4e-8cc3-28d0003ff428
		summarizeBy: sum
		sourceColumn: Order Item Quantity

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 95465474-155b-42c0-9986-1a6dc5e24eab
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column 'Order Item Total'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9e4554c8-c5f1-4f3e-a163-e14203d26933
		summarizeBy: sum
		sourceColumn: Order Item Total

		annotation SummarizationSetBy = Automatic

	column 'Order Profit Per Order'
		dataType: int64
		formatString: 0
		lineageTag: c4068810-c490-43f2-a0de-64c885054ffa
		summarizeBy: sum
		sourceColumn: Order Profit Per Order

		annotation SummarizationSetBy = Automatic

	column 'Order Region'
		dataType: string
		lineageTag: ec1904c1-7749-4fa8-89ea-50202bec30ff
		summarizeBy: none
		sourceColumn: Order Region

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		lineageTag: 161cef7d-1cf0-4a49-9ed0-44312b8438ee
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		lineageTag: 4e19c9cc-f01d-4703-9a0c-7f140c1ff92f
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	column 'Order Zipcode'
		dataType: int64
		formatString: 0
		lineageTag: d485089f-1172-4365-875b-8db435d7973d
		summarizeBy: sum
		sourceColumn: Order Zipcode

		annotation SummarizationSetBy = Automatic

	column 'Product Card Id'
		dataType: int64
		formatString: 0
		lineageTag: 097778c3-ebff-4f50-8431-8aceaa66ca9e
		summarizeBy: count
		sourceColumn: Product Card Id

		annotation SummarizationSetBy = Automatic

	column 'Product Category Id'
		dataType: int64
		formatString: 0
		lineageTag: 5aa6cc24-41bb-4a07-b7c9-b2ae9d52fe29
		summarizeBy: count
		sourceColumn: Product Category Id

		annotation SummarizationSetBy = Automatic

	column 'Product Description'
		dataType: string
		lineageTag: 72bfae01-251e-4d73-a8b9-d25ce35e5655
		summarizeBy: none
		sourceColumn: Product Description

		annotation SummarizationSetBy = Automatic

	column 'Product Image'
		dataType: string
		lineageTag: 776c4f34-565d-4aa9-b6cb-cdfa78480717
		summarizeBy: none
		sourceColumn: Product Image

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 1682dce8-9275-4863-bd0a-9f325b1f2cd9
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Price'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 27d01dc5-5b32-4228-9414-c1130ba1d34f
		summarizeBy: sum
		sourceColumn: Product Price

		annotation SummarizationSetBy = Automatic

	column 'Product Status'
		dataType: int64
		formatString: 0
		lineageTag: 0377d3d0-293e-4017-bde7-0a9ced66d19d
		summarizeBy: sum
		sourceColumn: Product Status

		annotation SummarizationSetBy = Automatic

	column 'shipping date (DateOrders)'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 604b25e1-30c6-43f4-a2a8-ab8b597248c5
		summarizeBy: none
		sourceColumn: shipping date (DateOrders)

		variation Variation
			isDefault
			relationship: cb3d14db-d7f0-436f-9f06-9e7ccdb660dc
			defaultHierarchy: LocalDateTable_6cc43d06-e844-4eac-8e7b-68f6d6481500.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Shipping Mode'
		dataType: string
		lineageTag: 1d45e62a-9193-4e09-8faa-23444097fad6
		summarizeBy: none
		sourceColumn: Shipping Mode

		annotation SummarizationSetBy = Automatic

	partition DataCoSupplyChainDataset_transformed = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Git\Github\DataCo-SupplyChain-Analysis\data\DataCoSupplyChainDataset_transformed.csv"),[Delimiter=",", Columns=53, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Type", type text}, {"Days for shipping (real)", Int64.Type}, {"Days for shipment (scheduled)", Int64.Type}, {"Benefit per order", Int64.Type}, {"Sales per customer", Int64.Type}, {"Delivery Status", type text}, {"Late_delivery_risk", Int64.Type}, {"Category Id", Int64.Type}, {"Category Name", type text}, {"Customer City", type text}, {"Customer Country", type text}, {"Customer Email", type text}, {"Customer Fname", type text}, {"Customer Id", Int64.Type}, {"Customer Lname", type text}, {"Customer Password", type text}, {"Customer Segment", type text}, {"Customer State", type text}, {"Customer Street", type text}, {"Customer Zipcode", Int64.Type}, {"Department Id", Int64.Type}, {"Department Name", type text}, {"Latitude", Int64.Type}, {"Longitude", Int64.Type}, {"Market", type text}, {"Order City", type text}, {"Order Country", type text}, {"Order Customer Id", Int64.Type}, {"order date (DateOrders)", type date}, {"Order Id", Int64.Type}, {"Order Item Cardprod Id", Int64.Type}, {"Order Item Discount", Int64.Type}, {"Order Item Discount Rate", Int64.Type}, {"Order Item Id", Int64.Type}, {"Order Item Product Price", Int64.Type}, {"Order Item Profit Ratio", Int64.Type}, {"Order Item Quantity", Int64.Type}, {"Sales", Int64.Type}, {"Order Item Total", Int64.Type}, {"Order Profit Per Order", Int64.Type}, {"Order Region", type text}, {"Order State", type text}, {"Order Status", type text}, {"Order Zipcode", Int64.Type}, {"Product Card Id", Int64.Type}, {"Product Category Id", Int64.Type}, {"Product Description", type text}, {"Product Image", type text}, {"Product Name", type text}, {"Product Price", Int64.Type}, {"Product Status", Int64.Type}, {"shipping date (DateOrders)", type date}, {"Shipping Mode", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

