table DescriptionDataCoSupplyChain
	lineageTag: 3f920462-5cca-44ee-a594-48f20b03fa04

	column FIELDS
		dataType: string
		lineageTag: 117272f1-2439-4ee6-9a55-fadc93178fd7
		summarizeBy: none
		sourceColumn: FIELDS

		annotation SummarizationSetBy = Automatic

	column DESCRIPTION
		dataType: string
		lineageTag: 8de52089-1e8f-4d5b-81a4-fbad8c5f5781
		summarizeBy: none
		sourceColumn: DESCRIPTION

		annotation SummarizationSetBy = Automatic

	partition DescriptionDataCoSupplyChain = m
		mode: import
		source =
				let
				    Fonte =
				        Csv.Document(
				            File.Contents("C:\Git\Github\DataCo-SupplyChain-Analysis\datasets\DataCo_Smart_Supply\DescriptionDataCoSupplyChain.csv"),
				            [Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]
				        ),
				
				    // Tipagem inicial
				    #"Tipo Alterado" =
				        Table.TransformColumnTypes(
				            Fonte,
				            {{"Column1", type text}, {"Column2", type text}}
				        ),
				
				    // Promove cabeçalhos
				    #"Cabeçalhos Promovidos" =
				        Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				
				    // Garante tipo texto
				    #"Tipo Alterado1" =
				        Table.TransformColumnTypes(
				            #"Cabeçalhos Promovidos",
				            {{"FIELDS", type text}, {"DESCRIPTION", type text}}
				        ),
				
				    // Remove ":" e espaços extras da descrição
				    #"Descricao Limpa" =
				        Table.TransformColumns(
				            #"Tipo Alterado1",
				            {
				                {
				                    "DESCRIPTION",
				                    each Text.Trim(Text.Replace(_, ":", "")),
				                    type text
				                }
				            }
				        )
				in
				    #"Descricao Limpa"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

