table DescriptionDataCoSupplyChain
	lineageTag: 3f920462-5cca-44ee-a594-48f20b03fa04

	column FIELDS
		dataType: string
		lineageTag: 117272f1-2439-4ee6-9a55-fadc93178fd7
		summarizeBy: none
		sourceColumn: FIELDS

		annotation SummarizationSetBy = Automatic

	column DESCRIPTION
		dataType: string
		lineageTag: 8de52089-1e8f-4d5b-81a4-fbad8c5f5781
		summarizeBy: none
		sourceColumn: DESCRIPTION

		annotation SummarizationSetBy = Automatic

	partition DescriptionDataCoSupplyChain = m
		mode: import
		source = ```
				let
				    // Alteração da fonte: de local (File.Contents) para Web (Web.Contents)
				    // Importante usar a URL do raw.githubusercontent
				    Fonte = 
				        Csv.Document(
				            Web.Contents("https://raw.githubusercontent.com/gustavolima007/DataCo-SupplyChain-Analysis/refs/heads/main/data/DescriptionDataCoSupplyChain.csv"),
				            [Delimiter=",", Columns=53, Encoding=65001, QuoteStyle=QuoteStyle.None]
				        ),
				
				    // Tipagem inicial
				    #"Tipo Alterado" =
				        Table.TransformColumnTypes(
				            Fonte,
				            {{"Column1", type text}, {"Column2", type text}}
				        ),
				
				    // Promove cabeçalhos
				    #"Cabeçalhos Promovidos" =
				        Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				
				    // Garante tipo texto
				    #"Tipo Alterado1" =
				        Table.TransformColumnTypes(
				            #"Cabeçalhos Promovidos",
				            {{"FIELDS", type text}, {"DESCRIPTION", type text}}
				        ),
				
				    // Remove ":" e espaços extras da descrição
				    #"Descricao Limpa" =
				        Table.TransformColumns(
				            #"Tipo Alterado1",
				            {
				                {
				                    "DESCRIPTION",
				                    each Text.Trim(Text.Replace(_, ":", "")),
				                    type text
				                }
				            }
				        ),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Descricao Limpa",{"", "_1", "_2", "_3", "_4", "_5", "_6", "_7", "_8", "_9", "_10", "_11", "_12", "_13", "_14", "_15", "_16", "_17", "_18", "_19", "_20", "_21", "_22", "_23", "_24", "_25", "_26", "_27", "_28", "_29", "_30", "_31", "_32", "_33", "_34", "_35", "_36", "_37", "_38", "_39", "_40", "_41", "_42", "_43", "_44", "_45", "_46", "_47", "_48", "_49", "_50"})
				in
				    #"Colunas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

