table DescriptionDataCoSupplyChain
	lineageTag: 10986da6-b64b-43f6-b77d-162b0964c8c8

	column Column1
		dataType: string
		lineageTag: f3168135-00a9-4b92-9a31-c276427adff7
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 6792272a-ac69-4fe3-b876-8ef2d3dc49bd
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition DescriptionDataCoSupplyChain = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Git\Github\DataCo-SupplyChain-Analysis\datasets\DataCo_Smart_Supply\DescriptionDataCoSupplyChain.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

