table fato_vendas
	lineageTag: 3a2227c8-6fcf-4b01-bef9-630ee7ba409e

	column 'Data do Pedido'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e5b504f7-29d1-4596-b955-40f401cc3dcf
		summarizeBy: none
		sourceColumn: Data do Pedido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f9b70bf8-1cab-43d8-be29-84ced0cfca35
		summarizeBy: none
		sourceColumn: Data de Envio

		variation Variation
			isDefault
			relationship: 738e1857-904a-456d-87b0-6ff89a31deb1
			defaultHierarchy: LocalDateTable_03f298f8-7b6d-4e3a-bfd8-9a9f99005ec7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de Pagamento'
		dataType: string
		lineageTag: 5759cd26-9084-4787-a5d8-fd17a79c0c22
		summarizeBy: none
		sourceColumn: Tipo de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Dias Envio Real'
		dataType: int64
		formatString: 0
		lineageTag: 1c4d2365-a5a9-403b-8571-913d755e8d32
		summarizeBy: sum
		sourceColumn: Dias Envio Real

		annotation SummarizationSetBy = Automatic

	column 'Dias Envio Programado'
		dataType: int64
		formatString: 0
		lineageTag: 9b06fbdd-1c5a-4066-9466-d900c7f604b6
		summarizeBy: sum
		sourceColumn: Dias Envio Programado

		annotation SummarizationSetBy = Automatic

	column 'Risco de Atraso'
		dataType: int64
		lineageTag: c0fbbf16-61ec-4a56-98c9-e70cc7f17e8f
		summarizeBy: sum
		sourceColumn: Risco de Atraso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome da Categoria'
		dataType: string
		lineageTag: 6b6c01a0-a0f1-4ea2-9bdd-162e238712c0
		summarizeBy: none
		sourceColumn: Nome da Categoria

		annotation SummarizationSetBy = Automatic

	column 'Segmento do Cliente'
		dataType: string
		lineageTag: 5ca844e7-32ee-4fe9-9490-728e83b2fd0f
		summarizeBy: none
		sourceColumn: Segmento do Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome do Departamento'
		dataType: string
		lineageTag: 8e93acbb-dc98-44b7-9978-3218f2738e71
		summarizeBy: none
		sourceColumn: Nome do Departamento

		annotation SummarizationSetBy = Automatic

	column 'Cidade do Pedido'
		dataType: string
		lineageTag: 2e7b0569-f00e-4bfd-8895-07d950779706
		summarizeBy: none
		sourceColumn: Cidade do Pedido

		annotation SummarizationSetBy = Automatic

	column 'País do Pedido'
		dataType: string
		lineageTag: 9e75e3b5-1543-4142-aacc-235af3fc9fd7
		summarizeBy: none
		sourceColumn: País do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Região do Pedido'
		dataType: string
		lineageTag: 6014c761-5619-4ba6-810c-2a55fa9ade6b
		summarizeBy: none
		sourceColumn: Região do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Situação do Pedido'
		dataType: string
		lineageTag: 76576158-df58-435a-a4ce-5e7f5544208e
		summarizeBy: none
		sourceColumn: Situação do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Nome do Produto'
		dataType: string
		lineageTag: 6949bb3a-947f-4099-9d0e-afc8434d7273
		summarizeBy: none
		sourceColumn: Nome do Produto

		annotation SummarizationSetBy = Automatic

	column Vendas
		dataType: double
		lineageTag: 426498e2-9e87-4eb0-b680-a9dc4daef8c1
		summarizeBy: sum
		sourceColumn: Vendas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lucro do Pedido'
		dataType: double
		lineageTag: 8c3a33d5-983b-4d77-9bbe-ff6156c64cde
		summarizeBy: sum
		sourceColumn: Lucro do Pedido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ID do Pedido'
		dataType: int64
		formatString: 0
		lineageTag: 861ec635-d295-4e08-ba3b-a67d95647f1a
		summarizeBy: sum
		sourceColumn: ID do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Mercado Global'
		dataType: string
		lineageTag: 64e981c1-aaee-42c4-9faa-1ec49e1e35b2
		summarizeBy: none
		sourceColumn: Mercado Global

		annotation SummarizationSetBy = Automatic

	column 'Modalidade de Entrega'
		dataType: string
		lineageTag: e8999890-cdd0-4d18-8d64-40d059651b54
		summarizeBy: none
		sourceColumn: Modalidade de Entrega

		annotation SummarizationSetBy = Automatic

	column 'Status do Pedido'
		dataType: string
		lineageTag: 58d17272-4416-4017-8ec9-153cab3511c4
		summarizeBy: none
		sourceColumn: Status do Pedido

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: string
		lineageTag: ae54ab98-74d2-4ffd-bdbd-538db6f99e1e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column 'No Prazo Flag' = IF(fato_vendas[Dias Envio Real] <= fato_vendas[Dias Envio Programado], 1, 0)
		formatString: 0
		lineageTag: 996bb7b5-8f3f-47ab-9355-e84038038db8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_vendas = m
		mode: import
		source = ```
				let
				    Fonte = DataCoSupplyChainDataset,
				    
				    // Seleção e Renomeação inicial
				    ColunasSelecionadas = Table.SelectColumns(Fonte, {
				        "order date (DateOrders)", "shipping date (DateOrders)", "Type", 
				        "Days for shipping (real)", "Days for shipment (scheduled)", 
				        "Delivery Status", "Late_delivery_risk", "Category Name", 
				        "Customer Segment", "Department Name", "Market", "Order City", 
				        "Order Country", "Order Region", "Order Status", "Product Name", 
				        "Sales", "Order Profit Per Order", "Shipping Mode", "Order Id"
				    }),
				
				    // Garantindo tipos de dados corretos
				    AjustarTipos = Table.TransformColumnTypes(ColunasSelecionadas, {
				        {"order date (DateOrders)", type date}, 
				        {"shipping date (DateOrders)", type date},
				        {"Sales", type number},
				        {"Order Profit Per Order", type number}
				    }),
				
				    // Traduções de Mercado
				    TraduzirMercado = Table.AddColumn(AjustarTipos, "Mercado Global", each 
				        if [Market] = "Europe" then "Europa"
				        else if [Market] = "Pacific Asia" then "Ásia-Pacífico"
				        else if [Market] = "LATAM" then "América Latina"
				        else if [Market] = "Africa" then "África"
				        else if [Market] = "USCA" then "EUA e Canadá"
				        else [Market], type text),
				
				    // Bandeira da Região
				    AdicionarBandeira = Table.AddColumn(TraduzirMercado, "Flag", each
				        if [Mercado Global] = "Europa" then "https://flagcdn.com/w40/eu.png"
				        else if [Mercado Global] = "Ásia-Pacífico" then "https://flagcdn.com/w40/un.png"
				        else if [Mercado Global] = "América Latina" then "https://flagcdn.com/w40/br.png"
				        else if [Mercado Global] = "África" then "https://flagcdn.com/w40/za.png"
				        else if [Mercado Global] = "EUA e Canadá" then "https://raw.githubusercontent.com/gustavolima007/DataCo-SupplyChain-Analysis/main/figma/eua-ca.png"
				        else null, type text),
				
				    // Traduções de Modalidade
				    TraduzirModalidade = Table.AddColumn(AdicionarBandeira, "Modalidade de Entrega", each 
				        if [Shipping Mode] = "First Class" then "Primeira Classe"
				        else if [Shipping Mode] = "Second Class" then "Segunda Classe"
				        else if [Shipping Mode] = "Standard Class" then "Classe Padrão"
				        else if [Shipping Mode] = "Same Day" then "Entrega no Mesmo Dia"
				        else [Shipping Mode], type text),
				
				    // Traduções de Status
				    TraduzirStatus = Table.AddColumn(TraduzirModalidade, "Status do Pedido", each 
				        if [Delivery Status] = "Shipping on time" then "No Prazo"
				        else if [Delivery Status] = "Late delivery" then "Em Atraso"
				        else if [Delivery Status] = "Shipping canceled" then "Cancelado"
				        else if [Delivery Status] = "Advance shipping" then "Antecipado"
				        else [Delivery Status], type text),
				
				    // Renomeação Final
				    RenomearGeral = Table.RenameColumns(TraduzirStatus, {
				        {"order date (DateOrders)", "Data do Pedido"},
				        {"shipping date (DateOrders)", "Data de Envio"},
				        {"Days for shipping (real)", "Dias Envio Real"},
				        {"Days for shipment (scheduled)", "Dias Envio Programado"},
				        {"Order Profit Per Order", "Lucro do Pedido"},
				        {"Sales", "Vendas"},
				        {"Type", "Tipo de Pagamento"},
				        {"Category Name", "Nome da Categoria"},
				        {"Customer Segment", "Segmento do Cliente"},
				        {"Department Name", "Nome do Departamento"},
				        {"Order City", "Cidade do Pedido"},
				        {"Order Country", "País do Pedido"},
				        {"Order Region", "Região do Pedido"},
				        {"Order Status", "Situação do Pedido"},
				        {"Product Name", "Nome do Produto"},
				        {"Order Id", "ID do Pedido"},
				        {"Late_delivery_risk", "Risco de Atraso"}
				    }),
				    
				    // Removendo colunas em inglês
				    RemoverIngles = Table.RemoveColumns(RenomearGeral,{"Market", "Shipping Mode", "Delivery Status"})
				in
				    RemoverIngles
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

