table tokenized_access_logs
	lineageTag: 1824a1ff-04b7-4852-a38d-0349737e17de

	column Product
		dataType: string
		lineageTag: 260f3311-c503-469f-bf87-efaad7464b38
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 10e39407-882f-4f43-ae66-119736eb917e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2ce0f9e3-55b0-49b4-acfe-623fa4447ab5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: cc91dfbf-fc11-4d35-9ca0-76dc75a0486f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: 7f71aa75-1010-40a0-bc78-c670127aff19
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 7449094e-7db5-462e-9536-c1a7f0cb10ad
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column ip
		dataType: int64
		formatString: 0
		lineageTag: c9b0cd34-d25b-41b3-8717-aa51ebfc896b
		summarizeBy: sum
		sourceColumn: ip

		annotation SummarizationSetBy = Automatic

	partition tokenized_access_logs = m
		mode: import
		source = ```
				let
				    // Alteração da fonte: de local (File.Contents) para Web (Web.Contents)
				    // Importante usar a URL do raw.githubusercontent
				    Fonte = 
				        Csv.Document(
				            Web.Contents("https://raw.githubusercontent.com/gustavolima007/DataCo-SupplyChain-Analysis/refs/heads/main/datasets/DataCo_Smart_Supply/tokenized_access_logs.csv"),
				            [Delimiter=",", Columns=53, Encoding=65001, QuoteStyle=QuoteStyle.None]
				        ),
				    
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Product", type text}, {"Category", type text}, {"Date", type datetime}, {"Month", type text}, {"Hour", Int64.Type}, {"Department", type text}, {"ip", Int64.Type}, {"url", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"url", "", "_1", "_2", "_3", "_4", "_5", "_6", "_7", "_8", "_9", "_10", "_11", "_12", "_13", "_14", "_15", "_16", "_17", "_18", "_19", "_20", "_21", "_22", "_23", "_24", "_25", "_26", "_27", "_28", "_29", "_30", "_31", "_32", "_33", "_34", "_35", "_36", "_37", "_38", "_39", "_40", "_41", "_42", "_43", "_44"})
				in
				    #"Colunas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

